### ISSUE TITLE
Create seperate stylesheets for the panel and the feedback modal

### ISSUE THREAD

**Issue by chalalala** [chalalala/Green-Us#10]
Because these components will appear in many pages, maybe I should create a stylesheet for each of them so that it can be used in many pages and we don't have to copy it to each page and edit many times whenever there is a change.

**Comment by chalalala** [comment]
I have just separated the stylesheet for the feedback part

**Comment by chalalala** [comment]
Done with both

**Comment by provodoihi** [comment]
Fix for issue #8
