### ISSUE TITLE
[Panel] Remove duplicate parts

### ISSUE THREAD

**Issue by chalalala** [chalalala/Green-Us#14]
As I have just separated the stylesheet for the panel, its code in the stylesheet of each page is no longer needed.
Could you please remove this part in each stylesheet (except the panel.css)
```
/* Panel */
#panel{
	width:80px;
	height:100%;
	
	position: relative;
	float:left;
	margin-left:-70;
	
	z-index:1;
}

@keyframes mymove{
  from {left: 0px;}
  to {left: 70px;}
}

#panel:hover{
	animation: mymove 1.5s;
	animation-fill-mode: both;
}

.icon{
	width:60px;
	height:60px;
	background-color:white;
	border-radius:50%;
	
	margin:9px;
	text-align:center;
	
}

.icon img{
	width:100%;
	height:100%;
	border-radius:50%;
	object-fit:cover;
	
	display:inline-block;
    margin-top:2px;
}
```
and add `<link href="css/panel.css" rel="stylesheet">` to the header of their HTML (as I did in main_page.html)

**NOTE:** The panel is not available in diary, index, info_plant, sign up, sign in, resetpass so you don't need to change them!

**Comment by provodoihi** [comment]
Okay, I will do it

**Comment by provodoihi** [comment]
Done with this issue. You can check if there is any error
