### ISSUE TITLE
Need a weather page

### ISSUE THREAD

**Issue by chalalala** [chalalala/Green-Us#2]
This page must include information like weather, temperature, moisture, humidity, precipitation, and (maybe) a list of plants suitable to plant at that condition (anyway, I think it's more complex so this part can be done later).

**Comment by chalalala** [comment]
I have just done the weather forecast page with its basic features (date, temperature, humidity, etc.). But then I realized that my design style changes based on my mood so it looks not really related to other pages.. (except the index one lol). Maybe I will change them soon.

**Comment by dracarys1312** [comment]
Is this done or need more improvement?
