### ISSUE TITLE
How to not saving password in plaintext?

### ISSUE THREAD

**Issue by dracarys1312** [chalalala/Green-Us#20]
We need to find some solutions because we can't just save password in plain text in our database. Any thoughts guys?

**Comment by chalalala** [comment]
I've just done some search. Maybe we can try to [add salt to hashing](https://auth0.com/blog/adding-salt-to-hashing-a-better-way-to-store-passwords/) so saving password might be more secure. It seems like the most common method.

**Comment by provodoihi** [comment]
Do you mean using encryption method to save password in our database @dracarys1312

**Comment by dracarys1312** [comment]
So I have figure it out and applied it to our code. Close issue
