### ISSUE TITLE
Testing with Cypress

### ISSUE THREAD

**Issue by chalalala** [chalalala/Green-Us#21]
Maybe we could have a try with Cypress as Dr. Truong Anh Hoang suggested. Even though I know @dracarys1312  already had other methods for testing). It's ok to try a new thing, right? If it succeeds, then we will know a new helpful tool.

**Comment by provodoihi** [comment]
@chalalala  I agree with you, let see if that tool is helpful or not

**Comment by chalalala** [comment]
Hey, I think it could be helpful if we have to test something like a text input. For example, in some test cases, there are changes in one input box and the others are the same but of course, we won't want to type the same thing again and again. Then we could use this, just copy the code and change the part we want to change. *(if I got it correctly lol)*

**Comment by provodoihi** [comment]
@chalalala Okay, I will wait for your code testing result

**Comment by provodoihi** [comment]
@chalalala I see the code testing result, the tool is pretty good
