### ISSUE TITLE
[Profile] Display issues

### ISSUE THREAD

**Issue by provodoihi** [chalalala/Green-Us#22]
When I tried to figure out the components of the page by using inspect, the feedback button seem to move in other location that is unexpected 

![image](https://user-images.githubusercontent.com/59214604/79829828-49083e00-83ce-11ea-91b8-7b0f84aa1cc0.png)

**Comment by chalalala** [comment]
Actually, according to what I see from your screen there is a problem with the whole display not only the feedback button :') Ok let me check it.

**Comment by chalalala** [comment]
I've tried my best to fix it. Hope that there's no more error...
