### ISSUE TITLE
[News] Find some interesting articles for the news page

### ISSUE THREAD

**Issue by chalalala** [chalalala/Green-Us#28]
I want to find some news to embed to the news page. You can put some suggestion here.

**Comment by chalalala** [comment]
Example: [Bring biodiversity back to your garden to help save the planet](https://www.independent.co.uk/property/gardening/rewilding-gardening-biodiversity-insects-native-species-a9356941.html)

**Comment by provodoihi** [comment]
I suggest this page: [7 Science-Backed Health Benefits of Having Plants at Home](https://www.ecowatch.com/health-benefits-of-having-plants-at-home-2608386260.html)
