### ISSUE TITLE
[Dictionary] Change font for dictionary page

### ISSUE THREAD

**Issue by chalalala** [chalalala/Green-Us#29]
I'm thinking of changing the font in the page Dictionary to another font, maybe ABeeZe 'cause some people said the current font looks hard.

If change the font to ABeeZe, it will look like this

![image](https://user-images.githubusercontent.com/49138712/80314620-baa41a00-881c-11ea-8dec-6943897b4931.png)

Is that ok or we should change to the other one or keep the old one?

**Comment by provodoihi** [comment]
@chalalala If you have some esay to read local fonts, you can try with it. The fonts are provided by Figma seem to have their limit

**Comment by chalalala** [comment]
Ehmm I think you're misunderstanding me. I'm asking if ABeeZee looks better than the current one or we should keep it or choosing another font?

**Comment by provodoihi** [comment]
@chalalala Oh, okay, so we can change to AZeeBee if it is better

**Comment by chalalala** [comment]
Ok I changed it
