### ISSUE TITLE
[Panel] Update Panel

### ISSUE THREAD

**Issue by chalalala** [chalalala/Green-Us#38]
There were some changes to our website recently
1. Rename collection page (#36)
2. Create a News page (#31)

That's why we need to update our panel now. In particular, we have to update the link to each page in the panel.
All you have to do is replace the old panel part in each page with this. You can see the News page I'm going to push now as an example.
```
		<div id="panel">
			<div class="icon"><a href="profile.html"><img src="images/avatar.jpg"></a></div>
			<div class="icon"><a href="collection.html"><img src="images/icons/garden.png"></a></div>
			<div class="icon"><a href="dictionary.html"><img src="images/icons/dictionary.png"></a></div>
			<div class="icon"><a href="weather.html"><img src="images/icons/weather.png"></a></div>
			<div class="icon"><a href="news.html"><img src="images/news.png"></a></div>
		</div>
```

**Comment by provodoihi** [comment]
@chalalala Okay I see and I will do it soon

**Comment by provodoihi** [comment]
@chalalala I have done the task, can you check it?
