### ISSUE TITLE
Some parts haven't been designed yet

### ISSUE THREAD

**Issue by chalalala** [chalalala/Green-Us#4]
I just write here to remind us (include myself) that we haven't had the design of
- [x] News page
- [x] Feedback (a button and a popup window)

**Comment by chalalala** [comment]
I've done the Weather page but still haven't had a design for News page yet. Could you help me @provodoihi ? Try to draft something in Figma.

**Comment by provodoihi** [comment]
@chalalala Okay, I will try it soon

**Comment by provodoihi** [comment]
@chalalala I have recently uploaded the draft design in Figma, can you check it?

**Comment by chalalala** [comment]
Ok, I saw it. But I don't think that makes it exactly the same as other pages is a good idea (except when they have a similar function and format of content) even though you copy from two different pages and combine them to a new page... Try something more creative.

**Comment by chalalala** [comment]
Furthermore, I just intend to link to the news/article, display something like titles and descriptions, not include all of the content in our pages. Sorry... It was my fault for not making it clear...

**Comment by chalalala** [comment]
I've just done my design on Figma but I'm not sure the font looks good. Please check it and maybe look for a better one if you find it weird in some ways like me.

**Comment by provodoihi** [comment]
Okay, I have checked it and the design is pretty good. So that issue done
