### ISSUE TITLE
[Loader] Add loader to all pages

### ISSUE THREAD

**Issue by chalalala** [chalalala/Green-Us#40]
I've just created a loader for the website (#27) but I haven't made it available in all the pages yet. So this is a new work for you.
1. Open each HTML file
2. Add these two lines to the **<head\>** of the HTML *(MUST be the head not any other part)*
```
<link href="css/loader.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
```
3. Add this line to the **<body\>**
`<div id="loader"></div>`
4. Put everything (**EXCEPT** the <script\> parts and <style\> part if any) into a 
`<div id="content"></div>`
5. Add this line after that
`<script src="javascript/loader.js"></script>`

You can find an example in [**news.html**](https://github.com/chalalala/Green-Us/blob/master/news.html) that I've done.

### There are quite many steps so **BE CAREFUL!!**

**Comment by provodoihi** [comment]
@chalalala Okay, I will do it soon
