### ISSUE TITLE
[Loader] Display issue

### ISSUE THREAD

**Issue by provodoihi** [chalalala/Green-Us#43]
In these page: Index, Signin and Signup, the loader seems to be malfunction like this 

![image](https://user-images.githubusercontent.com/59214604/80719486-bc742300-8b25-11ea-9973-7a613fef3a4f.png)

**Comment by chalalala** [comment]
I found the problem. When you did the index, signup, signin and resetpass pages, I don't know why but you put a </div> at the end of the <image\> line. That's why the error occurs when you create a new div outside.
