### ISSUE TITLE
Fix the textarea in feedback modal

### ISSUE THREAD

**Issue by chalalala** [chalalala/Green-Us#8]
The textarea in feedback modal looks nice on my screen but have some troubles on @provodoihi  screen. It's may because of the number of columns I set. Maybe I need to find another approach for sizing the textarea.

**Comment by chalalala** [comment]
Instead of using cols and rows, I set the width and height in the stylesheet. The width is in percentage and aligned center so it can avoid difference between browser. Please check it @provodoihi .

**Comment by provodoihi** [comment]
It is ok now
