### ISSUE TITLE
Update SDD document

### ISSUE THREAD

**Issue by chalalala** [chalalala/Green-Us#9]
There were some changes in the design so the document needs to be updated.

**Comment by provodoihi** [comment]
I have recently made some changes in the SDD document. @chalalala can you check it for me

**Comment by chalalala** [comment]
@provodoihi Ok let me check

**Comment by chalalala** [comment]
It seems good but you missed some attributes in the Weather part. I have just completed it. And in the Record of change table, we haven't released yet so I don't think our changes can be counted as a new version (e.g: 1.0, 1.1, etc.)
